version: '3'
services:
    web:
        container_name: montech
        image: ${DOCKER_REGISTRY}montech
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: always
        volumes:
            - .:/var/www/html
        env_file:
            - ./.env
        ports:
            - "${PHP_PORT}:80"
        tty: true
        stdin_open: true
        extra_hosts:
            - "dockerhost:127.0.0.1"
